server:
  PortServer: :5000

secretService:
  JwtSecretKey: secretkey

mysql:
  MysqlHost:     localhost
  MysqlPort:     3306
  MysqlUser:     root
  MysqlPassword: 1234
  MysqlDbname:   db
  MysqlDriver:   mysql

postgres:
  PostgresqlHost: localhost
  PostgresqlPort: 5433
  PostgresqlUser: postgres
  PostgresqlPassword: postgres
  PostgresqlDbname: db
  PgDriver: pgx